apiVersion: v1
kind: Namespace
metadata:
  name: mi-proyecto-nginx
---
# --- DEPLOYMENT BACK ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-primer-deployment
  namespace: mi-proyecto-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: web
        image: nginx:latest
        command: [ "sh", "-c", "echo \"Pod BACK: $(hostname)\" > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'" ]
        ports:
        - containerPort: 80
          name: http-web
---
# --- SERVICE BACK ---
apiVersion: v1
kind: Service
metadata:
  name: service-back
  namespace: mi-proyecto-nginx
spec:
  type: NodePort
  selector:
    app: back
  ports:
    - name: http-web
      port: 8080
      targetPort: 80
      nodePort: 30080
---
# --- DEPLOYMENT FRONT ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-segundo-deployment
  namespace: mi-proyecto-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: web
        image: nginx:latest
        command: [ "sh", "-c", "echo \"Pod FRONT: $(hostname)\" > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'" ]
        ports:
        - containerPort: 80
          name: http-web
---
# --- SERVICE FRONT ---
apiVersion: v1
kind: Service
metadata:
  name: service-front
  namespace: mi-proyecto-nginx
spec:
  type: NodePort
  selector:
    app: front
  ports:
    - name: http-web
      port: 80
      targetPort: 80
      nodePort: 30081
