apiVersion: v1
kind: Namespace
metadata:
  name: mi-proyecto-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-primer-deployment
  namespace: mi-proyecto-nginx
  annotations:
    kubernetes.io/change-cause: "imagen nginx:latest"
  labels:
    app: mi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: web
        image: nginx:latest
        command: [ "sh", "-c", "echo \"Pod hostname: $(hostname)\" > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'" ]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: custom-node-port-service
  namespace: mi-proyecto-nginx
  annotations:
    prometheus.io/scrape: "true"   # <--- Esto le da permiso
    prometheus.io/port: "80"       # <--- El puerto donde está nginx
spec:
  type: NodePort
  selector:
    app: back
  ports:
    - name: http-web
      protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitor
  namespace: mi-proyecto-nginx # Donde está tu Nginx
  labels:
    release: monitoring # IMPORTANTE: Este label debe coincidir con el de tu instalación de Prometheus
spec:
  selector:
    matchLabels:
      app: back # Debe coincidir con el selector de tu Service
  endpoints:
  - port: http-web # Es el nombre o número del puerto en tu Service
    interval: 15s
